/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author mustafa
 */
public class Start extends javax.swing.JFrame {

    private boolean option = true;
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        optionX = new javax.swing.JToggleButton();
        optionO = new javax.swing.JToggleButton();
        startFirst = new javax.swing.JToggleButton();
        start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(600, 300));
        setMinimumSize(new java.awt.Dimension(200, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 90, 16);

        playerName.setText("Player");
        getContentPane().add(playerName);
        playerName.setBounds(30, 50, 150, 28);

        optionX.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        optionX.setSelected(true);
        optionX.setText("X");
        optionX.setMaximumSize(new java.awt.Dimension(75, 75));
        optionX.setMinimumSize(new java.awt.Dimension(75, 75));
        optionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionXActionPerformed(evt);
            }
        });
        getContentPane().add(optionX);
        optionX.setBounds(30, 90, 70, 70);

        optionO.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        optionO.setText("O");
        optionO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOActionPerformed(evt);
            }
        });
        getContentPane().add(optionO);
        optionO.setBounds(110, 90, 70, 70);

        startFirst.setSelected(true);
        startFirst.setText("Start First");
        getContentPane().add(startFirst);
        startFirst.setBounds(100, 170, 90, 29);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(60, 210, 75, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        String playerName = this.playerName.getText();
        boolean startFirst = this.startFirst.isSelected();
        char optionPlayer = 'O';
        char optionCpu = 'X';
        if (this.option) {
            optionPlayer = 'X';
            optionCpu = 'O';
        }
        Game game = new Game();
        Game.setStartPlayer(startFirst);
        Game.setOptionPlayer(optionPlayer);
        Game.setOptionCpu(optionCpu);
        Game.setPlayerName(playerName);
        game.setVisible(true);
        game.start();
        this.setVisible(false);
    }//GEN-LAST:event_startActionPerformed

    private void optionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionXActionPerformed
        if (optionO.isSelected()) {
            optionO.setSelected(false);
        }
        this.option = true;
    }//GEN-LAST:event_optionXActionPerformed

    private void optionOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionOActionPerformed
        if (optionX.isSelected()) {
            optionX.setSelected(false);
        }
        this.option = false;
    }//GEN-LAST:event_optionOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton optionO;
    private javax.swing.JToggleButton optionX;
    private javax.swing.JTextField playerName;
    private javax.swing.JButton start;
    private javax.swing.JToggleButton startFirst;
    // End of variables declaration//GEN-END:variables
}
